# Generated by Django 5.2.3 on 2025-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
